window.RedmineApp = window.RedmineApp || {};
window.RedmineApp.dom = window.RedmineApp.dom || {};

window.RedmineApp.dom.getElements = function getElements() {
  return {
    menuToggle: document.getElementById('menuToggle'),
    menuPanel: document.getElementById('menuPanel'),
    viewTasksBtn: document.getElementById('viewTasksBtn'),
    viewDetailBtn: document.getElementById('viewDetailBtn'),
    viewLogsBtn: document.getElementById('viewLogsBtn'),
    viewSettingsBtn: document.getElementById('viewSettingsBtn'),
    tasksView: document.getElementById('tasksView'),
    detailView: document.getElementById('detailView'),
    logsView: document.getElementById('logsView'),
    settingsView: document.getElementById('settingsView'),
    detailTitle: document.getElementById('detailTitle'),
    detailStatus: document.getElementById('detailStatus'),
    detailFacts: document.getElementById('detailFacts'),
    detailDescription: document.getElementById('detailDescription'),
    detailAttachments: document.getElementById('detailAttachments'),
    detailExtra: document.getElementById('detailExtra'),
    configForm: document.getElementById('configForm'),
    baseUrl: document.getElementById('baseUrl'),
    apiKey: document.getElementById('apiKey'),
    userId: document.getElementById('userId'),
    activityId: document.getElementById('activityId'),
    issueQuery: document.getElementById('issueQuery'),
    themeMode: document.getElementById('themeMode'),
    configStatus: document.getElementById('configStatus'),
    refreshBtn: document.getElementById('refreshBtn'),
    issuesCount: document.getElementById('issuesCount'),
    issuesList: document.getElementById('issuesList'),
    globalStatus: document.getElementById('globalStatus'),
    timerIssue: document.getElementById('timerIssue'),
    timerElapsed: document.getElementById('timerElapsed'),
    timerComment: document.getElementById('timerComment'),
    timerSpentOn: document.getElementById('timerSpentOn'),
    timerActivityId: document.getElementById('timerActivityId'),
    stopAndLogBtn: document.getElementById('stopAndLogBtn'),
    discardTimerBtn: document.getElementById('discardTimerBtn'),
    timerStatus: document.getElementById('timerStatus'),
    manualIssueId: document.getElementById('manualIssueId'),
    manualHours: document.getElementById('manualHours'),
    manualSpentOn: document.getElementById('manualSpentOn'),
    manualComment: document.getElementById('manualComment'),
    manualActivityId: document.getElementById('manualActivityId'),
    logManualBtn: document.getElementById('logManualBtn'),
    manualStatus: document.getElementById('manualStatus'),
    selectedIssueLabel: document.getElementById('selectedIssueLabel'),
    loadEntriesBtn: document.getElementById('loadEntriesBtn'),
    entriesBody: document.getElementById('entriesBody'),
    logsPath: document.getElementById('logsPath'),
    logsRefreshBtn: document.getElementById('logsRefreshBtn'),
    logsClearBtn: document.getElementById('logsClearBtn'),
    logsExportBtn: document.getElementById('logsExportBtn'),
    logLevelFilter: document.getElementById('logLevelFilter'),
    logSourceFilter: document.getElementById('logSourceFilter'),
    logErrorTypeFilter: document.getElementById('logErrorTypeFilter'),
    logDateFrom: document.getElementById('logDateFrom'),
    logDateTo: document.getElementById('logDateTo'),
    logSearchFilter: document.getElementById('logSearchFilter'),
    logsBody: document.getElementById('logsBody'),
    logsStatus: document.getElementById('logsStatus'),
  };
};
